use DotNetKurs

insert into ispitanici (ime, prezime, broj_pregleda, pol, starost, grad)
values
    ('Stefana', 'Kanovic', 8, 'Z', 74, 'Novi Sad'),
    ('Jelisaveta', 'Pijetlovic', 10, 'Z', 64, 'Zrenjanin'),
    ('Sanja', 'Markovic', 7, 'Z', 28, 'Novi Sad'),
    ('Dionizij', 'Pijetlovic', 3, 'M', 52, 'Nis'),
    ('Aleksandar', 'Nikolic', 4, 'M', 18, 'Zrenjanin'),
    ('Milica', 'Misic', 1, 'Z', 67, 'Nis'),
    ('Petar', 'Nenadic', 0, 'M', 38, 'Nis'),
    ('Katarina', 'Kamenko', 11, 'Z', 51, 'Novi Sad'),
    ('Vuk', 'Pijetlovic', 9, 'M', 53, 'Zrenjanin'),
    ('Zeljko', 'Nenadic', 13, 'M', 62, 'Zrenjanin'),
    ('Milan', 'Paroski', 5, 'M', 50, 'Zrenjanin'),
    ('Milan', 'Jocic', 5, 'M', 44, 'Novi Sad'),
    ('Marina', 'Mikic', 5, 'Z', 44, 'Nis'),
    ('Arsenija', 'Jocic', 10, 'Z', 62, 'Beograd'),
    ('Zoran', 'Dulovic', 5, 'M', 50, 'Beograd'),
    ('Marina', 'Markovic', 1, 'Z', 40, 'Nis'),
    ('Marija', 'Tomic', 4, 'Z', 39, 'Novi Sad'),
    ('Dionizij', 'Bosnjak', 4, 'M', 39, 'Beograd'),
    ('Zarko', 'Markovic', 5, 'M', 42, 'Novi Sad'),
    ('Tanja', 'Tomic', 9, 'Z', 72, 'Novi Sad'),
    ('Marija', 'Pijetlovic', 7, 'Z', 22, 'Nis'),
    ('Jovana', 'Bosnjak', 2, 'Z', 27, 'Nis'),
    ('Simeon', 'Mikic', 4, 'M', 11, 'Nis'),
    ('Vukan', 'Zlatanovic', 6, 'M', 19, 'Zrenjanin'),
    ('Dragana', 'Kamenko', 8, 'Z', 71, 'Zrenjanin'),
    ('Tijana', 'Valosic', 7, 'Z', 52, 'Novi Sad'),
    ('Jelisaveta', 'Kamenko', 8, 'Z', 43, 'Novi Sad'),
    ('Jelisaveta', 'Kecman', 4, 'Z', 54, 'Nis'),
    ('Nikola', 'Tomic', 6, 'M', 79, 'Nis'),
    ('Jelisaveta', 'Pijetlovic', 5, 'Z', 55, 'Novi Sad'),
    ('Ugljesa', 'Opacic', 2, 'M', 10, 'Beograd'),
    ('Spomenka', 'Tomic', 5, 'Z', 54, 'Nis'),
    ('Milan', 'Kamenko', 6, 'M', 24, 'Novi Sad'),
    ('Ana', 'Tomic', 8, 'Z', 28, 'Novi Sad'),
    ('Marina', 'Zlatanovic', 4, 'Z', 25, 'Beograd'),
    ('Nenad', 'Kecman', 1, 'M', 45, 'Beograd'),
    ('Vukasine', 'Nikolic', 3, 'M', 52, 'Nis'),
    ('Jovana', 'Tomic', 3, 'Z', 32, 'Beograd'),
    ('Tijana', 'Bosnjak', 8, 'Z', 50, 'Zrenjanin'),
    ('Nenad', 'Opacic', 5, 'M', 60, 'Nis'),
    ('Dusan', 'Kanovic', 9, 'M', 66, 'Nis'),
    ('Zoran', 'Kanovic', 2, 'M', 69, 'Beograd'),
    ('Nikola', 'Nenadic', 8, 'M', 70, 'Zrenjanin'),
    ('Stefan', 'Kaprocki', 5, 'M', 78, 'Zrenjanin'),
    ('Marko', 'Pijetlovic', 3, 'M', 15, 'Novi Sad'),
    ('Danica', 'Kanovic', 10, 'Z', 28, 'Zrenjanin'),
    ('Arsenija', 'Nikolic', 5, 'Z', 35, 'Nis'),
    ('Marija', 'Zlatanovic', 6, 'Z', 20, 'Novi Sad'),
    ('Danica', 'Misic', 8, 'Z', 62, 'Zrenjanin'),
    ('Blagoje', 'Kamenko', 7, 'M', 53, 'Novi Sad'),
    ('Milica', 'Opacic', 7, 'Z', 22, 'Novi Sad'),
    ('Zeljko', 'Bosnjak', 5, 'M', 22, 'Novi Sad'),
    ('Petar', 'Lakic', 7, 'M', 61, 'Beograd'),
    ('Ana', 'Kaprocki', 3, 'Z', 79, 'Beograd'),
    ('Nenad', 'Kamenko', 6, 'M', 60, 'Zrenjanin'),
    ('Milan', 'Mikic', 8, 'M', 59, 'Beograd'),
    ('Irena', 'Misic', 8, 'Z', 24, 'Zrenjanin'),
    ('Danica', 'Dulovic', 3, 'Z', 31, 'Beograd'),
    ('Dragan', 'Zlatanovic', 7, 'M', 77, 'Novi Sad'),
    ('Dusan', 'Kecman', 4, 'M', 71, 'Zrenjanin'),
    ('Jelisaveta', 'Kamenko', 6, 'Z', 38, 'Zrenjanin'),
    ('Vuk', 'Rapaic', 4, 'M', 25, 'Beograd'),
    ('Milan', 'Misic', 10, 'M', 79, 'Zrenjanin'),
    ('Zeljko', 'Zlatanovic', 5, 'M', 24, 'Beograd'),
    ('Vesna', 'Nenadic', 6, 'Z', 31, 'Beograd'),
    ('Stefan', 'Misic', 2, 'M', 31, 'Nis'),
    ('Nenad', 'Rapaic', 6, 'M', 76, 'Nis'),
    ('Marina', 'Misic', 6, 'Z', 79, 'Zrenjanin'),
    ('Marko', 'Pijetlovic', 4, 'M', 79, 'Novi Sad'),
    ('Jovan', 'Markovic', 8, 'M', 79, 'Beograd'),
    ('Dragana', 'Markovic', 9, 'Z', 59, 'Beograd'),
    ('Spomenka', 'Nenadic', 3, 'Z', 39, 'Nis'),
    ('Blagoje', 'Kecman', 5, 'M', 69, 'Beograd'),
    ('Mirjana', 'Nikolic', 6, 'Z', 71, 'Nis'),
    ('Vukasine', 'Kaprocki', 2, 'M', 12, 'Beograd'),
    ('Arsenija', 'Tomic', 8, 'Z', 50, 'Novi Sad'),
    ('Blagoje', 'Bosnjak', 5, 'M', 60, 'Nis'),
    ('Mirjana', 'Rapaic', 9, 'Z', 36, 'Zrenjanin'),
    ('Vukan', 'Opacic', 5, 'M', 61, 'Beograd'),
    ('Simeon', 'Valosic', 8, 'M', 60, 'Novi Sad'),
    ('Vasilije', 'Misic', 2, 'M', 29, 'Zrenjanin'),
    ('Dragana', 'Kecman', 9, 'Z', 40, 'Beograd'),
    ('Dusan', 'Paroski', 4, 'M', 17, 'Novi Sad'),
    ('Nikola', 'Nikolic', 7, 'M', 66, 'Novi Sad'),
    ('Katarina', 'Nenadic', 3, 'Z', 39, 'Nis'),
    ('Ugljesa', 'Nikolic', 6, 'M', 54, 'Novi Sad'),
    ('Renata', 'Bosnjak', 9, 'Z', 60, 'Novi Sad'),
    ('Aleksandar', 'Tomic', 5, 'M', 32, 'Zrenjanin'),
    ('Stefana', 'Kanovic', 9, 'Z', 60, 'Nis'),
    ('Jovan', 'Kecman', 2, 'M', 19, 'Nis'),
    ('Dragana', 'Kamenko', 5, 'Z', 36, 'Beograd'),
    ('Jelisaveta', 'Lakic', 7, 'Z', 78, 'Beograd'),
    ('Milica', 'Tomic', 12, 'Z', 45, 'Zrenjanin'),
    ('Zarko', 'Zlatanovic', 1, 'M', 24, 'Nis'),
    ('Blagoje', 'Valosic', 6, 'M', 18, 'Zrenjanin'),
    ('Dionizij', 'Bosnjak', 4, 'M', 38, 'Beograd'),
    ('Vukasine', 'Jocic', 6, 'M', 12, 'Novi Sad'),
    ('Blagoje', 'Opacic', 5, 'M', 69, 'Zrenjanin'),
    ('Ugljesa', 'Bosnjak', 6, 'M', 64, 'Novi Sad'),
    ('Dijana', 'Opacic', 4, 'Z', 17, 'Nis'),
    ('Milica', 'Misic', 7, 'Z', 43, 'Novi Sad'),
    ('Katarina', 'Bosnjak', 10, 'Z', 52, 'Zrenjanin'),
    ('Jovana', 'Nikolic', 6, 'Z', 44, 'Zrenjanin'),
    ('Nenad', 'Mikic', 0, 'M', 48, 'Nis'),
    ('Spomenka', 'Kanovic', 4, 'Z', 68, 'Nis'),
    ('Zivojin', 'Pijetlovic', 1, 'M', 24, 'Beograd'),
    ('Zivojin', 'Opacic', 4, 'M', 35, 'Beograd'),
    ('Dijana', 'Kaprocki', 3, 'Z', 49, 'Nis'),
    ('Milos', 'Zlatanovic', 0, 'M', 20, 'Beograd'),
    ('Zivojin', 'Nenadic', 6, 'M', 20, 'Zrenjanin'),
    ('Jelisaveta', 'Jocic', 3, 'Z', 22, 'Novi Sad'),
    ('Dragan', 'Rapaic', 2, 'M', 13, 'Nis'),
    ('Marko', 'Markovic', 7, 'M', 75, 'Novi Sad'),
    ('Simeon', 'Mikic', 3, 'M', 23, 'Beograd'),
    ('Marija', 'Misic', 2, 'Z', 31, 'Beograd'),
    ('Vesna', 'Mikic', 5, 'Z', 75, 'Nis'),
    ('Ugljesa', 'Misic', 5, 'M', 46, 'Zrenjanin'),
    ('Ugljesa', 'Nenadic', 3, 'M', 45, 'Beograd'),
    ('Danica', 'Misic', 2, 'Z', 21, 'Nis'),
    ('Zeljko', 'Pijetlovic', 3, 'M', 35, 'Zrenjanin'),
    ('Luka', 'Mikic', 4, 'M', 36, 'Zrenjanin'),
    ('Marina', 'Misic', 7, 'Z', 25, 'Beograd'),
    ('Vesna', 'Misic', 7, 'Z', 64, 'Novi Sad'),
    ('Petar', 'Lakic', 3, 'M', 63, 'Beograd'),
    ('Simeon', 'Kamenko', 5, 'M', 52, 'Novi Sad'),
    ('Ilija', 'Kanovic', 0, 'M', 14, 'Nis'),
    ('Marko', 'Rapaic', 7, 'M', 18, 'Zrenjanin'),
    ('Ugljesa', 'Dulovic', 1, 'M', 28, 'Novi Sad'),
    ('Arsenija', 'Opacic', 6, 'Z', 20, 'Novi Sad'),
    ('Blagoje', 'Pijetlovic', 4, 'M', 79, 'Beograd'),
    ('Vesna', 'Misic', 11, 'Z', 69, 'Zrenjanin'),
    ('Zivojin', 'Paroski', 3, 'M', 69, 'Beograd'),
    ('Simeon', 'Opacic', 7, 'M', 60, 'Beograd'),
    ('Vuk', 'Kaprocki', 7, 'M', 70, 'Zrenjanin'),
    ('Ugljesa', 'Misic', 5, 'M', 28, 'Zrenjanin'),
    ('Ana', 'Zlatanovic', 10, 'Z', 64, 'Novi Sad'),
    ('Marija', 'Opacic', 5, 'Z', 38, 'Beograd'),
    ('Dijana', 'Nikolic', 10, 'Z', 76, 'Zrenjanin'),
    ('Dionizij', 'Kaprocki', 4, 'M', 47, 'Novi Sad'),
    ('Zivojin', 'Kamenko', 7, 'M', 40, 'Beograd'),
    ('Aleksandar', 'Nenadic', 3, 'M', 33, 'Beograd'),
    ('Jovan', 'Pijetlovic', 6, 'M', 62, 'Beograd'),
    ('Stefana', 'Kecman', 10, 'Z', 70, 'Novi Sad'),
    ('Ugljesa', 'Zlatanovic', 4, 'M', 45, 'Beograd'),
    ('Dragan', 'Kamenko', 0, 'M', 20, 'Beograd'),
    ('Marina', 'Kamenko', 10, 'Z', 19, 'Zrenjanin'),
    ('Zeljko', 'Kamenko', 5, 'M', 47, 'Novi Sad'),
    ('Vukasine', 'Valosic', 4, 'M', 70, 'Novi Sad'),
    ('Dijana', 'Opacic', 6, 'Z', 44, 'Beograd'),
    ('Zoran', 'Nikolic', 4, 'M', 53, 'Beograd'),
    ('Dragan', 'Pijetlovic', 5, 'M', 18, 'Beograd'),
    ('Petar', 'Kanovic', 5, 'M', 65, 'Beograd'),
    ('Zarko', 'Tomic', 5, 'M', 71, 'Beograd'),
    ('Spomenka', 'Kanovic', 8, 'Z', 71, 'Novi Sad'),
    ('Jovana', 'Dulovic', 6, 'Z', 72, 'Nis'),
    ('Tanja', 'Kaprocki', 3, 'Z', 35, 'Beograd'),
    ('Ana', 'Opacic', 3, 'Z', 36, 'Beograd'),
    ('Milos', 'Dulovic', 5, 'M', 62, 'Beograd'),
    ('Irena', 'Paroski', 12, 'Z', 73, 'Novi Sad'),
    ('Mirjana', 'Jocic', 7, 'Z', 65, 'Novi Sad'),
    ('Dionizij', 'Valosic', 1, 'M', 11, 'Nis'),
    ('Luka', 'Nenadic', 5, 'M', 30, 'Zrenjanin'),
    ('Katarina', 'Markovic', 8, 'Z', 70, 'Beograd'),
    ('Nenad', 'Kaprocki', 6, 'M', 52, 'Zrenjanin'),
    ('Vukan', 'Bosnjak', 11, 'M', 69, 'Zrenjanin'),
    ('Tijana', 'Paroski', 6, 'Z', 47, 'Novi Sad'),
    ('Spomenka', 'Tomic', 7, 'Z', 22, 'Novi Sad'),
    ('Ilija', 'Paroski', 2, 'M', 68, 'Nis'),
    ('Zarko', 'Nikolic', 4, 'M', 79, 'Beograd'),
    ('Katarina', 'Kamenko', 9, 'Z', 17, 'Zrenjanin'),
    ('Ugljesa', 'Zlatanovic', 5, 'M', 36, 'Novi Sad'),
    ('Nenad', 'Paroski', 3, 'M', 45, 'Novi Sad'),
    ('Dusan', 'Paroski', 2, 'M', 35, 'Beograd'),
    ('Marko', 'Nikolic', 5, 'M', 59, 'Beograd'),
    ('Tanja', 'Nikolic', 2, 'Z', 49, 'Nis'),
    ('Blagoje', 'Valosic', 8, 'M', 62, 'Zrenjanin'),
    ('Dragan', 'Opacic', 8, 'M', 56, 'Zrenjanin'),
    ('Dragan', 'Rapaic', 2, 'M', 43, 'Novi Sad'),
    ('Ugljesa', 'Paroski', 2, 'M', 39, 'Zrenjanin'),
    ('Vukasine', 'Nenadic', 6, 'M', 29, 'Zrenjanin'),
    ('Irena', 'Valosic', 9, 'Z', 75, 'Nis'),
    ('Blagoje', 'Kamenko', 6, 'M', 26, 'Novi Sad'),
    ('Zarko', 'Markovic', 5, 'M', 37, 'Zrenjanin'),
    ('Blagoje', 'Nenadic', 4, 'M', 17, 'Novi Sad'),
    ('Milica', 'Kamenko', 5, 'Z', 57, 'Nis'),
    ('Petar', 'Valosic', 7, 'M', 77, 'Zrenjanin'),
    ('Sanja', 'Dulovic', 8, 'Z', 63, 'Nis'),
    ('Renata', 'Tomic', 5, 'Z', 53, 'Nis'),
    ('Nenad', 'Valosic', 6, 'M', 36, 'Zrenjanin'),
    ('Aleksandar', 'Opacic', 1, 'M', 24, 'Zrenjanin'),
    ('Ilija', 'Lakic', 7, 'M', 75, 'Beograd'),
    ('Dragan', 'Kanovic', 5, 'M', 56, 'Beograd'),
    ('Simeon', 'Zlatanovic', 6, 'M', 52, 'Novi Sad'),
    ('Katarina', 'Mikic', 1, 'Z', 29, 'Nis'),
    ('Milos', 'Lakic', 6, 'M', 57, 'Novi Sad'),
    ('Vesna', 'Dulovic', 5, 'Z', 29, 'Nis'),
    ('Vukasine', 'Misic', 3, 'M', 47, 'Beograd'),
    ('Renata', 'Rapaic', 7, 'Z', 65, 'Beograd'),
    ('Milan', 'Kanovic', 6, 'M', 28, 'Novi Sad'),
    ('Stefana', 'Misic', 4, 'Z', 29, 'Novi Sad'),
    ('Simeon', 'Pijetlovic', 1, 'M', 40, 'Nis'),
    ('Zarko', 'Nenadic', 7, 'M', 69, 'Nis'),
    ('Spomenka', 'Bosnjak', 6, 'Z', 28, 'Zrenjanin'),
    ('Vasilije', 'Bosnjak', 3, 'M', 11, 'Beograd'),
    ('Marija', 'Opacic', 6, 'Z', 66, 'Beograd'),
    ('Milos', 'Opacic', 8, 'M', 56, 'Novi Sad'),
    ('Aleksandar', 'Pijetlovic', 7, 'M', 76, 'Beograd'),
    ('Vasilije', 'Zlatanovic', 2, 'M', 60, 'Nis'),
    ('Luka', 'Jocic', 7, 'M', 73, 'Nis'),
    ('Vasilije', 'Misic', 4, 'M', 15, 'Beograd'),
    ('Petar', 'Mikic', 1, 'M', 20, 'Beograd'),
    ('Petar', 'Misic', 4, 'M', 66, 'Nis'),
    ('Danica', 'Rapaic', 6, 'Z', 28, 'Novi Sad'),
    ('Danica', 'Rapaic', 5, 'Z', 49, 'Nis'),
    ('Ilija', 'Kaprocki', 2, 'M', 69, 'Novi Sad'),
    ('Petar', 'Zlatanovic', 4, 'M', 70, 'Nis'),
    ('Tijana', 'Valosic', 6, 'Z', 18, 'Zrenjanin'),
    ('Irena', 'Paroski', 8, 'Z', 62, 'Zrenjanin'),
    ('Dragana', 'Bosnjak', 9, 'Z', 19, 'Zrenjanin'),
    ('Vukasine', 'Misic', 10, 'M', 61, 'Novi Sad'),
    ('Nikola', 'Kamenko', 3, 'M', 69, 'Beograd'),
    ('Arsenija', 'Misic', 7, 'Z', 68, 'Beograd'),
    ('Arsenija', 'Nenadic', 7, 'Z', 22, 'Zrenjanin'),
    ('Arsenija', 'Bosnjak', 6, 'Z', 46, 'Nis'),
    ('Arsenija', 'Opacic', 7, 'Z', 40, 'Novi Sad'),
    ('Vukasine', 'Zlatanovic', 1, 'M', 66, 'Beograd'),
    ('Marko', 'Kanovic', 4, 'M', 40, 'Novi Sad'),
    ('Petar', 'Dulovic', 5, 'M', 52, 'Beograd'),
    ('Zoran', 'Kecman', 6, 'M', 78, 'Novi Sad'),
    ('Dusan', 'Misic', 0, 'M', 15, 'Nis'),
    ('Danica', 'Rapaic', 7, 'Z', 72, 'Beograd'),
    ('Dijana', 'Nenadic', 5, 'Z', 50, 'Novi Sad'),
    ('Dusan', 'Kaprocki', 1, 'M', 44, 'Beograd'),
    ('Irina', 'Opacic', 7, 'Z', 17, 'Beograd'),
    ('Zivojin', 'Lakic', 10, 'M', 55, 'Zrenjanin'),
    ('Jovana', 'Markovic', 4, 'Z', 76, 'Beograd'),
    ('Marija', 'Pijetlovic', 8, 'Z', 20, 'Zrenjanin'),
    ('Tijana', 'Tomic', 7, 'Z', 56, 'Beograd'),
    ('Sanja', 'Kecman', 5, 'Z', 16, 'Beograd'),
    ('Dragana', 'Jocic', 6, 'Z', 47, 'Novi Sad'),
    ('Stefana', 'Opacic', 4, 'Z', 71, 'Nis'),
    ('Stefana', 'Kamenko', 8, 'Z', 25, 'Zrenjanin'),
    ('Ilija', 'Misic', 3, 'M', 17, 'Novi Sad'),
    ('Vesna', 'Kecman', 10, 'Z', 65, 'Novi Sad'),
    ('Nikola', 'Misic', 6, 'M', 20, 'Beograd'),
    ('Ognjen', 'Bosnjak', 7, 'M', 63, 'Beograd'),
    ('Vukasine', 'Nikolic', 10, 'M', 69, 'Zrenjanin'),
    ('Jelisaveta', 'Tomic', 7, 'Z', 62, 'Zrenjanin'),
    ('Marko', 'Kanovic', 2, 'M', 32, 'Novi Sad'),
    ('Zoran', 'Paroski', 6, 'M', 16, 'Novi Sad'),
    ('Tijana', 'Pijetlovic', 1, 'Z', 15, 'Nis'),
    ('Ana', 'Nenadic', 3, 'Z', 16, 'Zrenjanin'),
    ('Dragan', 'Tomic', 2, 'M', 32, 'Beograd'),
    ('Tanja', 'Lakic', 9, 'Z', 62, 'Beograd'),
    ('Zoran', 'Dulovic', 2, 'M', 47, 'Beograd'),
    ('Katarina', 'Paroski', 6, 'Z', 23, 'Novi Sad'),
    ('Jovana', 'Kamenko', 6, 'Z', 73, 'Nis'),
    ('Irena', 'Lakic', 5, 'Z', 39, 'Beograd'),
    ('Jovana', 'Bosnjak', 3, 'Z', 35, 'Beograd'),
    ('Milica', 'Kecman', 7, 'Z', 63, 'Novi Sad'),
    ('Zarko', 'Opacic', 6, 'M', 69, 'Beograd'),
    ('Irena', 'Kaprocki', 6, 'Z', 49, 'Novi Sad'),
    ('Spomenka', 'Dulovic', 6, 'Z', 19, 'Beograd'),
    ('Luka', 'Pijetlovic', 6, 'M', 18, 'Zrenjanin'),
    ('Dragana', 'Rapaic', 9, 'Z', 74, 'Zrenjanin'),
    ('Nenad', 'Zlatanovic', 2, 'M', 39, 'Zrenjanin'),
    ('Danica', 'Markovic', 8, 'Z', 26, 'Beograd'),
    ('Stefan', 'Opacic', 8, 'M', 73, 'Beograd'),
    ('Ilija', 'Kamenko', 3, 'M', 52, 'Nis'),
    ('Vesna', 'Pijetlovic', 4, 'Z', 45, 'Beograd'),
    ('Luka', 'Kecman', 6, 'M', 16, 'Zrenjanin'),
    ('Dijana', 'Misic', 5, 'Z', 40, 'Novi Sad'),
    ('Milica', 'Paroski', 6, 'Z', 42, 'Novi Sad'),
    ('Ognjen', 'Nikolic', 9, 'M', 58, 'Zrenjanin'),
    ('Vasilije', 'Kecman', 5, 'M', 70, 'Zrenjanin'),
    ('Milan', 'Mikic', 7, 'M', 24, 'Zrenjanin'),
    ('Vuk', 'Lakic', 3, 'M', 11, 'Novi Sad'),
    ('Vukan', 'Pijetlovic', 4, 'M', 75, 'Nis'),
    ('Vukan', 'Kecman', 2, 'M', 51, 'Novi Sad'),
    ('Irina', 'Bosnjak', 3, 'Z', 44, 'Nis'),
    ('Vasilije', 'Valosic', 6, 'M', 75, 'Novi Sad'),
    ('Zeljko', 'Kanovic', 4, 'M', 12, 'Nis'),
    ('Zarko', 'Nenadic', 10, 'M', 53, 'Zrenjanin'),
    ('Mirjana', 'Paroski', 7, 'Z', 63, 'Novi Sad'),
    ('Tanja', 'Opacic', 7, 'Z', 23, 'Zrenjanin'),
    ('Renata', 'Zlatanovic', 5, 'Z', 68, 'Beograd'),
    ('Dragana', 'Lakic', 5, 'Z', 35, 'Nis'),
    ('Vesna', 'Paroski', 9, 'Z', 66, 'Nis'),
    ('Aleksandar', 'Misic', 6, 'M', 24, 'Zrenjanin'),
    ('Dusan', 'Nikolic', 4, 'M', 13, 'Beograd'),
    ('Milos', 'Tomic', 4, 'M', 58, 'Beograd'),
    ('Marina', 'Dulovic', 12, 'Z', 55, 'Zrenjanin'),
    ('Mirjana', 'Misic', 11, 'Z', 18, 'Zrenjanin'),
    ('Vukasine', 'Misic', 5, 'M', 70, 'Nis'),
    ('Milan', 'Zlatanovic', 8, 'M', 64, 'Novi Sad'),
    ('Tijana', 'Valosic', 9, 'Z', 60, 'Zrenjanin'),
    ('Dijana', 'Tomic', 4, 'Z', 27, 'Beograd'),
    ('Stefan', 'Bosnjak', 4, 'M', 44, 'Nis'),
    ('Dusan', 'Valosic', 7, 'M', 40, 'Beograd'),
    ('Danica', 'Kecman', 7, 'Z', 35, 'Zrenjanin'),
    ('Stefana', 'Markovic', 5, 'Z', 49, 'Nis'),
    ('Dragana', 'Pijetlovic', 5, 'Z', 42, 'Zrenjanin'),
    ('Mirjana', 'Kaprocki', 7, 'Z', 71, 'Nis'),
    ('Marina', 'Kecman', 4, 'Z', 18, 'Beograd'),
    ('Jovana', 'Mikic', 7, 'Z', 42, 'Beograd'),
    ('Dusan', 'Opacic', 4, 'M', 14, 'Novi Sad'),
    ('Dragan', 'Kaprocki', 2, 'M', 23, 'Beograd'),
    ('Aleksandar', 'Kaprocki', 0, 'M', 40, 'Nis'),
    ('Arsenija', 'Misic', 6, 'Z', 35, 'Zrenjanin'),
    ('Danica', 'Valosic', 5, 'Z', 34, 'Beograd'),
    ('Irena', 'Mikic', 12, 'Z', 71, 'Zrenjanin'),
    ('Vuk', 'Valosic', 5, 'M', 67, 'Zrenjanin'),
    ('Irena', 'Tomic', 6, 'Z', 57, 'Nis'),
    ('Vuk', 'Kanovic', 3, 'M', 10, 'Novi Sad'),
    ('Sanja', 'Zlatanovic', 9, 'Z', 41, 'Nis'),
    ('Dijana', 'Lakic', 4, 'Z', 30, 'Novi Sad'),
    ('Vasilije', 'Valosic', 7, 'M', 75, 'Zrenjanin'),
    ('Jelisaveta', 'Markovic', 12, 'Z', 58, 'Zrenjanin'),
    ('Arsenija', 'Kecman', 7, 'Z', 15, 'Novi Sad'),
    ('Milica', 'Pijetlovic', 5, 'Z', 36, 'Beograd'),
    ('Aleksandar', 'Nikolic', 2, 'M', 13, 'Nis'),
    ('Zarko', 'Kanovic', 4, 'M', 33, 'Novi Sad'),
    ('Marko', 'Nenadic', 2, 'M', 23, 'Zrenjanin'),
    ('Vuk', 'Nenadic', 2, 'M', 59, 'Novi Sad'),
    ('Milica', 'Valosic', 7, 'Z', 66, 'Novi Sad'),
    ('Milan', 'Jocic', 2, 'M', 11, 'Nis'),
    ('Dragana', 'Valosic', 8, 'Z', 70, 'Novi Sad'),
    ('Mirjana', 'Kaprocki', 7, 'Z', 69, 'Zrenjanin'),
    ('Dusan', 'Nenadic', 5, 'M', 65, 'Novi Sad'),
    ('Zoran', 'Valosic', 5, 'M', 76, 'Zrenjanin'),
    ('Marija', 'Kecman', 0, 'Z', 12, 'Nis'),
    ('Petar', 'Valosic', 3, 'M', 18, 'Zrenjanin'),
    ('Zeljko', 'Misic', 6, 'M', 72, 'Novi Sad'),
    ('Marko', 'Zlatanovic', 3, 'M', 19, 'Zrenjanin'),
    ('Jovan', 'Opacic', 3, 'M', 14, 'Novi Sad'),
    ('Dijana', 'Tomic', 7, 'Z', 22, 'Zrenjanin'),
    ('Milan', 'Bosnjak', 7, 'M', 36, 'Beograd'),
    ('Renata', 'Zlatanovic', 7, 'Z', 79, 'Nis'),
    ('Katarina', 'Jocic', 11, 'Z', 36, 'Zrenjanin'),
    ('Mirjana', 'Dulovic', 8, 'Z', 20, 'Novi Sad'),
    ('Zeljko', 'Markovic', 3, 'M', 32, 'Nis'),
    ('Milan', 'Nikolic', 0, 'M', 22, 'Beograd'),
    ('Jovana', 'Kanovic', 4, 'Z', 24, 'Novi Sad'),
    ('Tanja', 'Dulovic', 10, 'Z', 38, 'Zrenjanin'),
    ('Vesna', 'Opacic', 7, 'Z', 48, 'Zrenjanin'),
    ('Zivojin', 'Nenadic', 1, 'M', 79, 'Nis'),
    ('Danica', 'Paroski', 3, 'Z', 11, 'Zrenjanin'),
    ('Vukan', 'Zlatanovic', 3, 'M', 77, 'Beograd'),
    ('Ognjen', 'Valosic', 4, 'M', 53, 'Zrenjanin'),
    ('Nenad', 'Nenadic', 2, 'M', 49, 'Nis'),
    ('Tijana', 'Mikic', 3, 'Z', 34, 'Beograd'),
    ('Dijana', 'Tomic', 4, 'Z', 45, 'Novi Sad'),
    ('Jelisaveta', 'Tomic', 8, 'Z', 28, 'Zrenjanin'),
    ('Stefan', 'Nenadic', 2, 'M', 70, 'Nis'),
    ('Katarina', 'Kamenko', 0, 'Z', 43, 'Nis'),
    ('Dionizij', 'Dulovic', 5, 'M', 59, 'Novi Sad'),
    ('Milos', 'Lakic', 0, 'M', 30, 'Nis'),
    ('Marija', 'Kanovic', 7, 'Z', 64, 'Beograd'),
    ('Vukan', 'Mikic', 7, 'M', 14, 'Nis'),
    ('Arsenija', 'Rapaic', 7, 'Z', 30, 'Nis'),
    ('Dijana', 'Pijetlovic', 10, 'Z', 57, 'Beograd'),
    ('Nenad', 'Paroski', 6, 'M', 22, 'Zrenjanin'),
    ('Irina', 'Mikic', 10, 'Z', 74, 'Zrenjanin'),
    ('Marija', 'Tomic', 7, 'Z', 75, 'Nis'),
    ('Dionizij', 'Markovic', 2, 'M', 26, 'Beograd'),
    ('Irina', 'Pijetlovic', 2, 'Z', 11, 'Nis'),
    ('Blagoje', 'Nenadic', 6, 'M', 46, 'Nis'),
    ('Marija', 'Mikic', 7, 'Z', 39, 'Zrenjanin'),
    ('Ognjen', 'Nenadic', 2, 'M', 35, 'Beograd'),
    ('Dragana', 'Valosic', 11, 'Z', 76, 'Zrenjanin'),
    ('Milan', 'Paroski', 4, 'M', 72, 'Novi Sad'),
    ('Renata', 'Nenadic', 7, 'Z', 14, 'Zrenjanin'),
    ('Tanja', 'Kanovic', 7, 'Z', 11, 'Beograd'),
    ('Blagoje', 'Dulovic', 1, 'M', 24, 'Zrenjanin'),
    ('Jovan', 'Valosic', 8, 'M', 10, 'Beograd'),
    ('Zivojin', 'Lakic', 1, 'M', 27, 'Nis'),
    ('Vasilije', 'Paroski', 3, 'M', 60, 'Nis'),
    ('Dragana', 'Markovic', 7, 'Z', 55, 'Novi Sad'),
    ('Marija', 'Valosic', 13, 'Z', 74, 'Zrenjanin'),
    ('Irena', 'Tomic', 5, 'Z', 38, 'Novi Sad'),
    ('Dijana', 'Tomic', 7, 'Z', 59, 'Novi Sad'),
    ('Jovan', 'Tomic', 6, 'M', 18, 'Beograd'),
    ('Stefan', 'Jocic', 1, 'M', 10, 'Beograd'),
    ('Zivojin', 'Dulovic', 4, 'M', 27, 'Zrenjanin'),
    ('Jovan', 'Dulovic', 1, 'M', 73, 'Nis'),
    ('Ilija', 'Kamenko', 4, 'M', 56, 'Nis'),
    ('Marina', 'Nikolic', 5, 'Z', 20, 'Nis'),
    ('Tijana', 'Lakic', 4, 'Z', 71, 'Nis'),
    ('Dijana', 'Paroski', 9, 'Z', 24, 'Novi Sad'),
    ('Vukan', 'Zlatanovic', 6, 'M', 75, 'Beograd'),
    ('Jovan', 'Valosic', 5, 'M', 75, 'Novi Sad'),
    ('Irena', 'Misic', 5, 'Z', 32, 'Beograd'),
    ('Danica', 'Tomic', 8, 'Z', 72, 'Nis'),
    ('Ugljesa', 'Rapaic', 6, 'M', 75, 'Beograd'),
    ('Sanja', 'Tomic', 3, 'Z', 23, 'Novi Sad'),
    ('Arsenija', 'Zlatanovic', 8, 'Z', 61, 'Novi Sad'),
    ('Vuk', 'Valosic', 3, 'M', 40, 'Novi Sad'),
    ('Zeljko', 'Mikic', 7, 'M', 28, 'Novi Sad'),
    ('Aleksandar', 'Misic', 6, 'M', 31, 'Beograd'),
    ('Milica', 'Valosic', 4, 'Z', 32, 'Beograd'),
    ('Zivojin', 'Tomic', 4, 'M', 35, 'Zrenjanin'),
    ('Nikola', 'Zlatanovic', 4, 'M', 36, 'Beograd'),
    ('Danica', 'Paroski', 5, 'Z', 34, 'Zrenjanin'),
    ('Zoran', 'Markovic', 7, 'M', 47, 'Novi Sad'),
    ('Marina', 'Kanovic', 7, 'Z', 61, 'Nis'),
    ('Ugljesa', 'Dulovic', 5, 'M', 70, 'Novi Sad'),
    ('Dusan', 'Jocic', 4, 'M', 31, 'Zrenjanin'),
    ('Stefana', 'Kecman', 3, 'Z', 42, 'Novi Sad'),
    ('Nikola', 'Nenadic', 4, 'M', 45, 'Beograd'),
    ('Zoran', 'Valosic', 0, 'M', 47, 'Nis'),
    ('Irena', 'Kaprocki', 6, 'Z', 12, 'Beograd'),
    ('Marina', 'Kaprocki', 4, 'Z', 14, 'Novi Sad'),
    ('Irena', 'Paroski', 1, 'Z', 33, 'Nis'),
    ('Ana', 'Jocic', 5, 'Z', 73, 'Nis'),
    ('Aleksandar', 'Rapaic', 6, 'M', 51, 'Zrenjanin'),
    ('Zoran', 'Pijetlovic', 2, 'M', 35, 'Beograd'),
    ('Nenad', 'Kamenko', 7, 'M', 66, 'Zrenjanin'),
    ('Vukan', 'Nikolic', 7, 'M', 54, 'Nis'),
    ('Irina', 'Zlatanovic', 7, 'Z', 24, 'Beograd'),
    ('Dusan', 'Paroski', 5, 'M', 16, 'Novi Sad'),
    ('Petar', 'Kaprocki', 0, 'M', 15, 'Beograd'),
    ('Zeljko', 'Paroski', 3, 'M', 22, 'Zrenjanin'),
    ('Mirjana', 'Tomic', 13, 'Z', 35, 'Zrenjanin'),
    ('Sanja', 'Misic', 5, 'Z', 17, 'Beograd'),
    ('Dusan', 'Valosic', 5, 'M', 31, 'Zrenjanin'),
    ('Ilija', 'Lakic', 2, 'M', 23, 'Nis'),
    ('Ilija', 'Kanovic', 3, 'M', 42, 'Beograd'),
    ('Vesna', 'Kanovic', 5, 'Z', 53, 'Beograd'),
    ('Dragan', 'Tomic', 4, 'M', 65, 'Novi Sad'),
    ('Zeljko', 'Nikolic', 7, 'M', 62, 'Nis'),
    ('Vukasine', 'Mikic', 1, 'M', 31, 'Nis'),
    ('Ilija', 'Rapaic', 6, 'M', 78, 'Zrenjanin'),
    ('Jovana', 'Bosnjak', 5, 'Z', 24, 'Beograd'),
    ('Dragan', 'Bosnjak', 5, 'M', 56, 'Novi Sad'),
    ('Danica', 'Rapaic', 10, 'Z', 40, 'Novi Sad'),
    ('Irina', 'Markovic', 10, 'Z', 29, 'Zrenjanin'),
    ('Stefana', 'Lakic', 6, 'Z', 32, 'Novi Sad'),
    ('Simeon', 'Misic', 1, 'M', 15, 'Beograd'),
    ('Simeon', 'Mikic', 4, 'M', 19, 'Zrenjanin'),
    ('Mirjana', 'Opacic', 7, 'Z', 79, 'Nis'),
    ('Vuk', 'Rapaic', 1, 'M', 39, 'Zrenjanin'),
    ('Stefana', 'Nenadic', 8, 'Z', 29, 'Novi Sad'),
    ('Stefana', 'Nikolic', 6, 'Z', 17, 'Zrenjanin'),
    ('Vasilije', 'Lakic', 5, 'M', 53, 'Nis'),
    ('Vasilije', 'Nenadic', 4, 'M', 70, 'Nis'),
    ('Tanja', 'Bosnjak', 11, 'Z', 51, 'Beograd'),
    ('Katarina', 'Nenadic', 6, 'Z', 21, 'Novi Sad'),
    ('Jovana', 'Rapaic', 4, 'Z', 10, 'Nis'),
    ('Jovana', 'Nenadic', 8, 'Z', 20, 'Beograd'),
    ('Irina', 'Pijetlovic', 6, 'Z', 34, 'Zrenjanin'),
    ('Zivojin', 'Tomic', 6, 'M', 68, 'Zrenjanin'),
    ('Milan', 'Nenadic', 3, 'M', 12, 'Nis'),
    ('Jovana', 'Paroski', 6, 'Z', 18, 'Novi Sad'),
    ('Danica', 'Pijetlovic', 6, 'Z', 21, 'Nis'),
    ('Jovana', 'Kecman', 8, 'Z', 30, 'Zrenjanin'),
    ('Irena', 'Misic', 9, 'Z', 70, 'Zrenjanin'),
    ('Marko', 'Kanovic', 5, 'M', 17, 'Novi Sad'),
    ('Vukan', 'Kanovic', 5, 'M', 63, 'Novi Sad'),
    ('Petar', 'Kamenko', 6, 'M', 52, 'Nis'),
    ('Simeon', 'Dulovic', 2, 'M', 67, 'Novi Sad'),
    ('Jovana', 'Paroski', 4, 'Z', 12, 'Novi Sad'),
    ('Ugljesa', 'Opacic', 3, 'M', 14, 'Beograd'),
    ('Zeljko', 'Kecman', 7, 'M', 16, 'Zrenjanin'),
    ('Tanja', 'Lakic', 4, 'Z', 42, 'Zrenjanin'),
    ('Ana', 'Valosic', 10, 'Z', 18, 'Zrenjanin'),
    ('Dionizij', 'Kaprocki', 3, 'M', 26, 'Nis'),
    ('Zeljko', 'Paroski', 2, 'M', 31, 'Novi Sad'),
    ('Zeljko', 'Markovic', 4, 'M', 33, 'Novi Sad'),
    ('Vesna', 'Lakic', 3, 'Z', 45, 'Nis'),
    ('Katarina', 'Nenadic', 4, 'Z', 67, 'Beograd'),
    ('Ugljesa', 'Kaprocki', 7, 'M', 79, 'Nis'),
    ('Zoran', 'Paroski', 7, 'M', 21, 'Novi Sad'),
    ('Ugljesa', 'Nenadic', 7, 'M', 36, 'Beograd'),
    ('Ana', 'Jocic', 6, 'Z', 20, 'Beograd'),
    ('Ana', 'Kecman', 5, 'Z', 76, 'Nis'),
    ('Nikola', 'Nenadic', 6, 'M', 17, 'Zrenjanin'),
    ('Marina', 'Opacic', 11, 'Z', 67, 'Novi Sad'),
    ('Irina', 'Misic', 3, 'Z', 18, 'Beograd'),
    ('Katarina', 'Markovic', 9, 'Z', 56, 'Novi Sad'),
    ('Ana', 'Bosnjak', 7, 'Z', 59, 'Nis'),
    ('Zivojin', 'Misic', 5, 'M', 44, 'Novi Sad'),
    ('Ognjen', 'Dulovic', 5, 'M', 75, 'Nis'),
    ('Ognjen', 'Kanovic', 2, 'M', 43, 'Nis'),
    ('Aleksandar', 'Paroski', 7, 'M', 46, 'Zrenjanin'),
    ('Spomenka', 'Kanovic', 3, 'Z', 31, 'Nis'),
    ('Luka', 'Zlatanovic', 10, 'M', 57, 'Zrenjanin'),
    ('Dionizij', 'Kaprocki', 6, 'M', 16, 'Zrenjanin'),
    ('Nikola', 'Jocic', 0, 'M', 31, 'Nis'),
    ('Spomenka', 'Misic', 8, 'Z', 61, 'Novi Sad'),
    ('Ana', 'Kanovic', 6, 'Z', 17, 'Beograd'),
    ('Dijana', 'Mikic', 8, 'Z', 60, 'Nis'),
    ('Nikola', 'Kamenko', 7, 'M', 48, 'Zrenjanin'),
    ('Nikola', 'Nikolic', 4, 'M', 17, 'Beograd'),
    ('Dusan', 'Lakic', 4, 'M', 35, 'Zrenjanin'),
    ('Sanja', 'Lakic', 1, 'Z', 30, 'Beograd'),
    ('Marina', 'Tomic', 11, 'Z', 63, 'Zrenjanin'),
    ('Petar', 'Kecman', 2, 'M', 64, 'Nis'),
    ('Dusan', 'Markovic', 0, 'M', 68, 'Nis'),
    ('Jelisaveta', 'Pijetlovic', 7, 'Z', 52, 'Zrenjanin'),
    ('Zeljko', 'Paroski', 5, 'M', 60, 'Beograd'),
    ('Marija', 'Mikic', 7, 'Z', 54, 'Novi Sad'),
    ('Marina', 'Dulovic', 7, 'Z', 64, 'Nis'),
    ('Jovan', 'Mikic', 8, 'M', 67, 'Beograd'),
    ('Luka', 'Kamenko', 4, 'M', 21, 'Beograd'),
    ('Zeljko', 'Nenadic', 7, 'M', 73, 'Novi Sad'),
    ('Ognjen', 'Tomic', 5, 'M', 58, 'Nis'),
    ('Stefana', 'Zlatanovic', 7, 'Z', 25, 'Novi Sad'),
    ('Luka', 'Paroski', 0, 'M', 70, 'Nis'),
    ('Jovana', 'Markovic', 13, 'Z', 60, 'Novi Sad'),
    ('Ugljesa', 'Kamenko', 7, 'M', 73, 'Zrenjanin'),
    ('Petar', 'Kecman', 1, 'M', 45, 'Nis'),
    ('Petar', 'Kecman', 8, 'M', 66, 'Novi Sad'),
    ('Jovana', 'Kanovic', 4, 'Z', 43, 'Beograd'),
    ('Zarko', 'Bosnjak', 6, 'M', 68, 'Zrenjanin'),
    ('Luka', 'Misic', 5, 'M', 21, 'Beograd'),
    ('Dusan', 'Kamenko', 5, 'M', 15, 'Nis'),
    ('Milos', 'Kamenko', 8, 'M', 67, 'Nis'),
    ('Blagoje', 'Dulovic', 4, 'M', 73, 'Nis'),
    ('Stefana', 'Zlatanovic', 6, 'Z', 48, 'Beograd'),
    ('Luka', 'Markovic', 4, 'M', 57, 'Beograd'),
    ('Milan', 'Lakic', 5, 'M', 45, 'Zrenjanin'),
    ('Stefana', 'Zlatanovic', 4, 'Z', 23, 'Nis'),
    ('Dionizij', 'Paroski', 4, 'M', 72, 'Beograd'),
    ('Ilija', 'Tomic', 5, 'M', 68, 'Nis'),
    ('Mirjana', 'Nikolic', 8, 'Z', 19, 'Novi Sad'),
    ('Danica', 'Paroski', 7, 'Z', 40, 'Nis'),
    ('Milica', 'Markovic', 5, 'Z', 13, 'Novi Sad'),
    ('Marija', 'Pijetlovic', 3, 'Z', 17, 'Zrenjanin'),
    ('Stefana', 'Markovic', 10, 'Z', 56, 'Novi Sad'),
    ('Simeon', 'Nikolic', 7, 'M', 60, 'Zrenjanin'),
    ('Spomenka', 'Dulovic', 7, 'Z', 68, 'Novi Sad'),
    ('Mirjana', 'Dulovic', 6, 'Z', 73, 'Novi Sad'),
    ('Katarina', 'Jocic', 11, 'Z', 59, 'Zrenjanin'),
    ('Sanja', 'Kanovic', 6, 'Z', 42, 'Zrenjanin'),
    ('Vuk', 'Mikic', 4, 'M', 40, 'Novi Sad'),
    ('Zoran', 'Kaprocki', 6, 'M', 43, 'Zrenjanin'),
    ('Jovana', 'Tomic', 3, 'Z', 25, 'Beograd'),
    ('Sanja', 'Paroski', 5, 'Z', 21, 'Novi Sad'),
    ('Vesna', 'Kanovic', 10, 'Z', 75, 'Novi Sad'),
    ('Luka', 'Kamenko', 5, 'M', 64, 'Beograd'),
    ('Jelisaveta', 'Paroski', 5, 'Z', 71, 'Nis'),
    ('Stefana', 'Misic', 4, 'Z', 14, 'Nis'),
    ('Vukan', 'Kamenko', 5, 'M', 52, 'Novi Sad'),
    ('Zarko', 'Nikolic', 3, 'M', 19, 'Nis'),
    ('Tanja', 'Rapaic', 4, 'Z', 65, 'Nis'),
    ('Sanja', 'Nikolic', 9, 'Z', 78, 'Novi Sad'),
    ('Mirjana', 'Kaprocki', 11, 'Z', 70, 'Novi Sad'),
    ('Milan', 'Bosnjak', 4, 'M', 28, 'Novi Sad'),
    ('Zeljko', 'Jocic', 2, 'M', 36, 'Beograd'),
    ('Jovan', 'Bosnjak', 6, 'M', 61, 'Zrenjanin'),
    ('Petar', 'Nikolic', 4, 'M', 19, 'Zrenjanin'),
    ('Ana', 'Lakic', 5, 'Z', 22, 'Novi Sad'),
    ('Marija', 'Markovic', 7, 'Z', 25, 'Novi Sad'),
    ('Aleksandar', 'Nenadic', 5, 'M', 48, 'Zrenjanin'),
    ('Spomenka', 'Lakic', 8, 'Z', 74, 'Beograd'),
    ('Simeon', 'Jocic', 4, 'M', 51, 'Novi Sad'),
    ('Stefan', 'Zlatanovic', 3, 'M', 53, 'Novi Sad'),
    ('Vukan', 'Rapaic', 6, 'M', 70, 'Beograd'),
    ('Dijana', 'Markovic', 3, 'Z', 29, 'Beograd'),
    ('Dijana', 'Mikic', 6, 'Z', 74, 'Nis'),
    ('Stefan', 'Zlatanovic', 7, 'M', 21, 'Zrenjanin'),
    ('Marija', 'Paroski', 6, 'Z', 11, 'Novi Sad'),
    ('Tanja', 'Paroski', 4, 'Z', 64, 'Beograd'),
    ('Vuk', 'Lakic', 6, 'M', 38, 'Beograd'),
    ('Milan', 'Jocic', 8, 'M', 26, 'Zrenjanin'),
    ('Jovana', 'Opacic', 6, 'Z', 32, 'Beograd'),
    ('Vesna', 'Kanovic', 4, 'Z', 33, 'Beograd'),
    ('Dragana', 'Zlatanovic', 3, 'Z', 68, 'Nis'),
    ('Danica', 'Rapaic', 10, 'Z', 48, 'Novi Sad'),
    ('Dragan', 'Zlatanovic', 5, 'M', 25, 'Novi Sad'),
    ('Dragan', 'Valosic', 8, 'M', 79, 'Beograd'),
    ('Katarina', 'Markovic', 0, 'Z', 46, 'Beograd'),
    ('Petar', 'Lakic', 5, 'M', 70, 'Beograd'),
    ('Ognjen', 'Kamenko', 2, 'M', 40, 'Nis'),
    ('Zoran', 'Misic', 6, 'M', 48, 'Beograd'),
    ('Dijana', 'Mikic', 10, 'Z', 47, 'Beograd'),
    ('Tijana', 'Tomic', 0, 'Z', 11, 'Nis'),
    ('Jelisaveta', 'Valosic', 3, 'Z', 39, 'Beograd'),
    ('Irina', 'Markovic', 2, 'Z', 10, 'Novi Sad'),
    ('Sanja', 'Pijetlovic', 10, 'Z', 34, 'Novi Sad'),
    ('Petar', 'Paroski', 9, 'M', 14, 'Novi Sad'),
    ('Vesna', 'Lakic', 9, 'Z', 48, 'Zrenjanin'),
    ('Stefan', 'Tomic', 3, 'M', 16, 'Novi Sad'),
    ('Marina', 'Kaprocki', 6, 'Z', 38, 'Nis'),
    ('Marija', 'Jocic', 0, 'Z', 29, 'Nis'),
    ('Tijana', 'Rapaic', 4, 'Z', 34, 'Beograd'),
    ('Katarina', 'Lakic', 6, 'Z', 77, 'Nis'),
    ('Jovana', 'Pijetlovic', 8, 'Z', 30, 'Novi Sad'),
    ('Milica', 'Dulovic', 2, 'Z', 13, 'Nis'),
    ('Irena', 'Rapaic', 9, 'Z', 68, 'Zrenjanin'),
    ('Nikola', 'Valosic', 1, 'M', 20, 'Beograd'),
    ('Mirjana', 'Rapaic', 7, 'Z', 13, 'Zrenjanin'),
    ('Stefana', 'Kanovic', 6, 'Z', 43, 'Zrenjanin'),
    ('Ana', 'Markovic', 6, 'Z', 51, 'Zrenjanin'),
    ('Sanja', 'Opacic', 4, 'Z', 57, 'Beograd'),
    ('Stefan', 'Zlatanovic', 5, 'M', 36, 'Novi Sad'),
    ('Irina', 'Rapaic', 3, 'Z', 21, 'Beograd'),
    ('Vasilije', 'Kaprocki', 1, 'M', 37, 'Beograd'),
    ('Sanja', 'Mikic', 6, 'Z', 37, 'Novi Sad'),
    ('Stefana', 'Tomic', 10, 'Z', 60, 'Zrenjanin'),
    ('Milica', 'Lakic', 12, 'Z', 71, 'Novi Sad'),
    ('Zivojin', 'Kaprocki', 2, 'M', 43, 'Nis'),
    ('Milica', 'Markovic', 2, 'Z', 24, 'Nis'),
    ('Milan', 'Bosnjak', 3, 'M', 58, 'Beograd'),
    ('Jovana', 'Lakic', 7, 'Z', 70, 'Novi Sad'),
    ('Renata', 'Kanovic', 11, 'Z', 49, 'Zrenjanin'),
    ('Danica', 'Kamenko', 3, 'Z', 30, 'Novi Sad'),
    ('Dragana', 'Bosnjak', 9, 'Z', 21, 'Zrenjanin'),
    ('Arsenija', 'Nenadic', 2, 'Z', 10, 'Beograd'),
    ('Aleksandar', 'Opacic', 2, 'M', 47, 'Nis'),
    ('Dragan', 'Lakic', 2, 'M', 42, 'Novi Sad'),
    ('Irena', 'Lakic', 6, 'Z', 23, 'Nis'),
    ('Nikola', 'Bosnjak', 6, 'M', 24, 'Zrenjanin'),
    ('Vuk', 'Kecman', 4, 'M', 14, 'Beograd'),
    ('Aleksandar', 'Zlatanovic', 4, 'M', 13, 'Zrenjanin'),
    ('Irina', 'Kaprocki', 8, 'Z', 53, 'Zrenjanin'),
    ('Vasilije', 'Rapaic', 0, 'M', 49, 'Nis'),
    ('Vuk', 'Opacic', 3, 'M', 20, 'Zrenjanin'),
    ('Mirjana', 'Kecman', 10, 'Z', 66, 'Beograd'),
    ('Nenad', 'Dulovic', 5, 'M', 53, 'Beograd'),
    ('Vukan', 'Kaprocki', 6, 'M', 70, 'Novi Sad'),
    ('Nikola', 'Nenadic', 2, 'M', 24, 'Nis'),
    ('Stefana', 'Nikolic', 9, 'Z', 27, 'Novi Sad'),
    ('Ognjen', 'Markovic', 11, 'M', 54, 'Zrenjanin'),
    ('Dragana', 'Rapaic', 9, 'Z', 16, 'Beograd'),
    ('Tijana', 'Kecman', 1, 'Z', 41, 'Novi Sad'),
    ('Milica', 'Kanovic', 6, 'Z', 73, 'Nis'),
    ('Vesna', 'Lakic', 8, 'Z', 78, 'Beograd'),
    ('Nikola', 'Misic', 1, 'M', 28, 'Nis'),
    ('Ana', 'Nenadic', 4, 'Z', 27, 'Zrenjanin'),
    ('Ana', 'Pijetlovic', 8, 'Z', 63, 'Nis'),
    ('Mirjana', 'Dulovic', 9, 'Z', 41, 'Novi Sad'),
    ('Ilija', 'Bosnjak', 8, 'M', 56, 'Novi Sad'),
    ('Zeljko', 'Markovic', 7, 'M', 78, 'Zrenjanin'),
    ('Milan', 'Zlatanovic', 8, 'M', 18, 'Novi Sad'),
    ('Marina', 'Bosnjak', 5, 'Z', 63, 'Novi Sad'),
    ('Dragana', 'Zlatanovic', 9, 'Z', 72, 'Zrenjanin'),
    ('Danica', 'Rapaic', 6, 'Z', 28, 'Novi Sad'),
    ('Arsenija', 'Opacic', 2, 'Z', 48, 'Nis'),
    ('Jovan', 'Misic', 2, 'M', 39, 'Novi Sad'),
    ('Katarina', 'Misic', 8, 'Z', 72, 'Beograd'),
    ('Zoran', 'Lakic', 0, 'M', 22, 'Nis'),
    ('Marko', 'Jocic', 1, 'M', 44, 'Nis'),
    ('Danica', 'Kaprocki', 5, 'Z', 37, 'Zrenjanin'),
    ('Arsenija', 'Lakic', 6, 'Z', 65, 'Beograd'),
    ('Stefana', 'Zlatanovic', 6, 'Z', 64, 'Beograd'),
    ('Mirjana', 'Kecman', 7, 'Z', 69, 'Beograd'),
    ('Zoran', 'Bosnjak', 3, 'M', 66, 'Beograd'),
    ('Marija', 'Kaprocki', 5, 'Z', 49, 'Zrenjanin'),
    ('Nikola', 'Tomic', 8, 'M', 25, 'Novi Sad'),
    ('Jovana', 'Misic', 1, 'Z', 48, 'Beograd'),
    ('Vasilije', 'Kecman', 4, 'M', 23, 'Zrenjanin'),
    ('Sanja', 'Nenadic', 4, 'Z', 42, 'Nis'),
    ('Ugljesa', 'Kecman', 4, 'M', 76, 'Beograd'),
    ('Irena', 'Misic', 7, 'Z', 17, 'Novi Sad'),
    ('Milan', 'Kaprocki', 5, 'M', 56, 'Novi Sad'),
    ('Ilija', 'Misic', 4, 'M', 52, 'Nis'),
    ('Renata', 'Nenadic', 5, 'Z', 17, 'Novi Sad'),
    ('Irena', 'Kamenko', 9, 'Z', 53, 'Zrenjanin'),
    ('Aleksandar', 'Misic', 5, 'M', 67, 'Novi Sad'),
    ('Renata', 'Jocic', 7, 'Z', 29, 'Novi Sad'),
    ('Zeljko', 'Nikolic', 2, 'M', 42, 'Novi Sad'),
    ('Stefan', 'Dulovic', 9, 'M', 20, 'Zrenjanin'),
    ('Sanja', 'Kaprocki', 8, 'Z', 30, 'Beograd'),
    ('Mirjana', 'Kecman', 3, 'Z', 10, 'Nis'),
    ('Renata', 'Paroski', 2, 'Z', 47, 'Beograd'),
    ('Renata', 'Kecman', 9, 'Z', 59, 'Nis'),
    ('Jovana', 'Zlatanovic', 5, 'Z', 42, 'Novi Sad'),
    ('Katarina', 'Valosic', 8, 'Z', 54, 'Zrenjanin'),
    ('Mirjana', 'Kaprocki', 7, 'Z', 50, 'Novi Sad'),
    ('Simeon', 'Rapaic', 3, 'M', 41, 'Beograd'),
    ('Stefana', 'Misic', 4, 'Z', 24, 'Beograd'),
    ('Petar', 'Bosnjak', 0, 'M', 73, 'Nis'),
    ('Ilija', 'Mikic', 2, 'M', 10, 'Nis'),
    ('Aleksandar', 'Tomic', 2, 'M', 39, 'Zrenjanin'),
    ('Nenad', 'Rapaic', 0, 'M', 42, 'Beograd'),
    ('Danica', 'Valosic', 6, 'Z', 69, 'Beograd'),
    ('Milan', 'Valosic', 7, 'M', 50, 'Beograd'),
    ('Zeljko', 'Opacic', 2, 'M', 19, 'Beograd'),
    ('Tanja', 'Lakic', 8, 'Z', 61, 'Novi Sad'),
    ('Stefana', 'Lakic', 4, 'Z', 68, 'Novi Sad'),
    ('Aleksandar', 'Opacic', 9, 'M', 55, 'Zrenjanin'),
    ('Tijana', 'Nenadic', 8, 'Z', 72, 'Novi Sad'),
    ('Dragana', 'Kanovic', 4, 'Z', 35, 'Nis'),
    ('Aleksandar', 'Paroski', 4, 'M', 34, 'Novi Sad'),
    ('Mirjana', 'Tomic', 2, 'Z', 24, 'Nis'),
    ('Renata', 'Misic', 7, 'Z', 49, 'Novi Sad'),
    ('Luka', 'Zlatanovic', 3, 'M', 13, 'Beograd'),
    ('Irena', 'Kecman', 7, 'Z', 49, 'Nis'),
    ('Dionizij', 'Nenadic', 2, 'M', 74, 'Nis'),
    ('Jovana', 'Rapaic', 2, 'Z', 12, 'Nis'),
    ('Ognjen', 'Misic', 1, 'M', 10, 'Novi Sad'),
    ('Katarina', 'Nikolic', 4, 'Z', 32, 'Beograd'),
    ('Vukan', 'Pijetlovic', 6, 'M', 34, 'Novi Sad'),
    ('Milan', 'Zlatanovic', 1, 'M', 15, 'Nis'),
    ('Marina', 'Opacic', 7, 'Z', 12, 'Zrenjanin'),
    ('Marko', 'Kecman', 7, 'M', 23, 'Novi Sad'),
    ('Ognjen', 'Valosic', 5, 'M', 27, 'Nis'),
    ('Katarina', 'Kecman', 8, 'Z', 27, 'Novi Sad'),
    ('Tijana', 'Jocic', 4, 'Z', 21, 'Beograd'),
    ('Sanja', 'Nenadic', 10, 'Z', 57, 'Novi Sad'),
    ('Zoran', 'Markovic', 8, 'M', 19, 'Zrenjanin'),
    ('Spomenka', 'Valosic', 6, 'Z', 48, 'Novi Sad'),
    ('Ognjen', 'Nenadic', 4, 'M', 62, 'Beograd'),
    ('Ana', 'Nikolic', 7, 'Z', 55, 'Novi Sad'),
    ('Marko', 'Kaprocki', 4, 'M', 64, 'Nis'),
    ('Milica', 'Opacic', 7, 'Z', 67, 'Beograd'),
    ('Ognjen', 'Opacic', 4, 'M', 18, 'Zrenjanin'),
    ('Vukan', 'Tomic', 3, 'M', 27, 'Novi Sad'),
    ('Marija', 'Paroski', 3, 'Z', 31, 'Beograd'),
    ('Jovan', 'Paroski', 4, 'M', 53, 'Nis'),
    ('Milica', 'Misic', 7, 'Z', 57, 'Nis'),
    ('Katarina', 'Opacic', 10, 'Z', 52, 'Novi Sad'),
    ('Ilija', 'Paroski', 2, 'M', 23, 'Zrenjanin'),
    ('Renata', 'Mikic', 3, 'Z', 66, 'Nis'),
    ('Nenad', 'Valosic', 5, 'M', 37, 'Nis'),
    ('Milica', 'Kaprocki', 7, 'Z', 44, 'Zrenjanin'),
    ('Zarko', 'Bosnjak', 5, 'M', 49, 'Zrenjanin'),
    ('Milos', 'Kamenko', 0, 'M', 30, 'Novi Sad'),
    ('Marko', 'Nenadic', 5, 'M', 24, 'Beograd'),
    ('Mirjana', 'Kaprocki', 7, 'Z', 75, 'Zrenjanin'),
    ('Mirjana', 'Tomic', 3, 'Z', 21, 'Beograd'),
    ('Ugljesa', 'Lakic', 1, 'M', 32, 'Zrenjanin'),
    ('Milos', 'Misic', 8, 'M', 48, 'Beograd'),
    ('Sanja', 'Lakic', 6, 'Z', 48, 'Nis'),
    ('Stefana', 'Nenadic', 6, 'Z', 74, 'Novi Sad'),
    ('Renata', 'Lakic', 9, 'Z', 47, 'Novi Sad'),
    ('Simeon', 'Rapaic', 1, 'M', 49, 'Nis'),
    ('Jovan', 'Nenadic', 1, 'M', 24, 'Nis'),
    ('Mirjana', 'Nenadic', 8, 'Z', 52, 'Novi Sad'),
    ('Petar', 'Mikic', 5, 'M', 39, 'Novi Sad'),
    ('Tijana', 'Mikic', 8, 'Z', 79, 'Zrenjanin'),
    ('Ognjen', 'Pijetlovic', 10, 'M', 52, 'Beograd'),
    ('Mirjana', 'Kamenko', 8, 'Z', 48, 'Novi Sad'),
    ('Vukan', 'Kecman', 3, 'M', 24, 'Beograd'),
    ('Dionizij', 'Pijetlovic', 6, 'M', 38, 'Beograd'),
    ('Vasilije', 'Paroski', 6, 'M', 34, 'Beograd'),
    ('Jovana', 'Kaprocki', 7, 'Z', 66, 'Zrenjanin'),
    ('Vukan', 'Valosic', 7, 'M', 51, 'Zrenjanin'),
    ('Nikola', 'Kecman', 1, 'M', 21, 'Novi Sad'),
    ('Tijana', 'Markovic', 4, 'Z', 21, 'Nis'),
    ('Zoran', 'Bosnjak', 3, 'M', 33, 'Novi Sad'),
    ('Zarko', 'Bosnjak', 7, 'M', 79, 'Zrenjanin'),
    ('Milica', 'Lakic', 3, 'Z', 30, 'Beograd'),
    ('Ana', 'Lakic', 6, 'Z', 32, 'Zrenjanin'),
    ('Sanja', 'Kanovic', 11, 'Z', 46, 'Beograd'),
    ('Dusan', 'Kecman', 4, 'M', 26, 'Zrenjanin'),
    ('Ugljesa', 'Kanovic', 3, 'M', 17, 'Novi Sad'),
    ('Arsenija', 'Misic', 7, 'Z', 71, 'Nis'),
    ('Arsenija', 'Rapaic', 6, 'Z', 48, 'Zrenjanin'),
    ('Arsenija', 'Kamenko', 6, 'Z', 73, 'Novi Sad'),
    ('Milan', 'Markovic', 1, 'M', 31, 'Nis'),
    ('Dragana', 'Bosnjak', 7, 'Z', 69, 'Novi Sad'),
    ('Dijana', 'Paroski', 6, 'Z', 73, 'Beograd'),
    ('Tanja', 'Lakic', 6, 'Z', 25, 'Novi Sad'),
    ('Blagoje', 'Valosic', 1, 'M', 27, 'Nis'),
    ('Tijana', 'Kaprocki', 4, 'Z', 32, 'Nis'),
    ('Irina', 'Kanovic', 5, 'Z', 67, 'Novi Sad'),
    ('Ugljesa', 'Valosic', 6, 'M', 23, 'Novi Sad'),
    ('Dionizij', 'Valosic', 3, 'M', 52, 'Beograd'),
    ('Zarko', 'Opacic', 3, 'M', 10, 'Novi Sad'),
    ('Blagoje', 'Kamenko', 7, 'M', 30, 'Novi Sad'),
    ('Mirjana', 'Nikolic', 8, 'Z', 53, 'Novi Sad'),
    ('Ana', 'Kamenko', 6, 'Z', 56, 'Nis'),
    ('Ognjen', 'Opacic', 5, 'M', 72, 'Zrenjanin'),
    ('Jovan', 'Zlatanovic', 0, 'M', 45, 'Nis'),
    ('Arsenija', 'Zlatanovic', 7, 'Z', 42, 'Beograd'),
    ('Aleksandar', 'Valosic', 10, 'M', 69, 'Zrenjanin'),
    ('Marko', 'Tomic', 4, 'M', 64, 'Beograd'),
    ('Spomenka', 'Pijetlovic', 1, 'Z', 12, 'Nis'),
    ('Marija', 'Tomic', 3, 'Z', 29, 'Nis'),
    ('Milica', 'Kaprocki', 4, 'Z', 30, 'Nis'),
    ('Tanja', 'Lakic', 8, 'Z', 56, 'Beograd'),
    ('Vukasine', 'Lakic', 4, 'M', 29, 'Beograd'),
    ('Dusan', 'Nikolic', 3, 'M', 31, 'Zrenjanin'),
    ('Luka', 'Jocic', 5, 'M', 64, 'Zrenjanin'),
    ('Dragan', 'Mikic', 2, 'M', 56, 'Beograd'),
    ('Nikola', 'Bosnjak', 2, 'M', 19, 'Beograd'),
    ('Tijana', 'Bosnjak', 7, 'Z', 31, 'Beograd'),
    ('Irena', 'Nikolic', 11, 'Z', 72, 'Beograd'),
    ('Marija', 'Misic', 11, 'Z', 70, 'Zrenjanin'),
    ('Simeon', 'Bosnjak', 2, 'M', 33, 'Beograd'),
    ('Marija', 'Nikolic', 10, 'Z', 71, 'Novi Sad'),
    ('Danica', 'Opacic', 6, 'Z', 23, 'Novi Sad'),
    ('Dijana', 'Kamenko', 8, 'Z', 68, 'Zrenjanin'),
    ('Marina', 'Kaprocki', 10, 'Z', 76, 'Zrenjanin'),
    ('Zarko', 'Nenadic', 7, 'M', 68, 'Beograd'),
    ('Jelisaveta', 'Zlatanovic', 9, 'Z', 35, 'Zrenjanin'),
    ('Ilija', 'Kamenko', 5, 'M', 30, 'Zrenjanin'),
    ('Mirjana', 'Lakic', 3, 'Z', 17, 'Nis'),
    ('Ilija', 'Kaprocki', 6, 'M', 55, 'Zrenjanin'),
    ('Milos', 'Valosic', 5, 'M', 57, 'Zrenjanin'),
    ('Irena', 'Kecman', 5, 'Z', 55, 'Novi Sad'),
    ('Marija', 'Lakic', 4, 'Z', 39, 'Nis'),
    ('Milan', 'Pijetlovic', 5, 'M', 26, 'Zrenjanin'),
    ('Irena', 'Pijetlovic', 7, 'Z', 66, 'Beograd'),
    ('Mirjana', 'Zlatanovic', 9, 'Z', 57, 'Beograd'),
    ('Dragana', 'Lakic', 8, 'Z', 69, 'Novi Sad'),
    ('Dionizij', 'Tomic', 1, 'M', 24, 'Beograd'),
    ('Sanja', 'Rapaic', 13, 'Z', 71, 'Zrenjanin'),
    ('Dragana', 'Nikolic', 4, 'Z', 41, 'Nis'),
    ('Arsenija', 'Rapaic', 1, 'Z', 12, 'Nis'),
    ('Tijana', 'Kanovic', 5, 'Z', 35, 'Beograd'),
    ('Ognjen', 'Zlatanovic', 3, 'M', 21, 'Nis'),
    ('Dragana', 'Nikolic', 10, 'Z', 68, 'Novi Sad'),
    ('Jelisaveta', 'Nikolic', 3, 'Z', 12, 'Nis'),
    ('Arsenija', 'Kanovic', 5, 'Z', 54, 'Beograd'),
    ('Jelisaveta', 'Kecman', 5, 'Z', 21, 'Beograd'),
    ('Danica', 'Pijetlovic', 10, 'Z', 77, 'Zrenjanin'),
    ('Dionizij', 'Kanovic', 0, 'M', 36, 'Nis'),
    ('Milos', 'Dulovic', 5, 'M', 48, 'Beograd'),
    ('Marina', 'Zlatanovic', 5, 'Z', 47, 'Novi Sad'),
    ('Zarko', 'Bosnjak', 3, 'M', 77, 'Novi Sad'),
    ('Spomenka', 'Valosic', 4, 'Z', 39, 'Beograd'),
    ('Vesna', 'Mikic', 8, 'Z', 65, 'Novi Sad'),
    ('Vukasine', 'Opacic', 1, 'M', 77, 'Nis'),
    ('Zeljko', 'Nikolic', 4, 'M', 47, 'Novi Sad'),
    ('Jovana', 'Mikic', 6, 'Z', 36, 'Novi Sad'),
    ('Irena', 'Dulovic', 10, 'Z', 68, 'Zrenjanin'),
    ('Luka', 'Kaprocki', 0, 'M', 12, 'Nis'),
    ('Ana', 'Nikolic', 7, 'Z', 75, 'Zrenjanin'),
    ('Simeon', 'Kaprocki', 5, 'M', 47, 'Nis'),
    ('Milan', 'Markovic', 4, 'M', 59, 'Nis'),
    ('Simeon', 'Kamenko', 2, 'M', 50, 'Nis'),
    ('Marija', 'Pijetlovic', 7, 'Z', 46, 'Zrenjanin'),
    ('Marija', 'Nenadic', 7, 'Z', 40, 'Novi Sad'),
    ('Renata', 'Jocic', 4, 'Z', 14, 'Nis'),
    ('Luka', 'Zlatanovic', 3, 'M', 65, 'Nis'),
    ('Zeljko', 'Kecman', 1, 'M', 11, 'Nis'),
    ('Stefana', 'Misic', 5, 'Z', 47, 'Beograd'),
    ('Vesna', 'Rapaic', 9, 'Z', 51, 'Zrenjanin'),
    ('Dijana', 'Bosnjak', 8, 'Z', 62, 'Zrenjanin'),
    ('Jelisaveta', 'Pijetlovic', 9, 'Z', 45, 'Zrenjanin'),
    ('Dijana', 'Jocic', 5, 'Z', 17, 'Beograd'),
    ('Vesna', 'Mikic', 5, 'Z', 72, 'Beograd'),
    ('Nikola', 'Valosic', 8, 'M', 64, 'Zrenjanin'),
    ('Petar', 'Nenadic', 1, 'M', 44, 'Beograd'),
    ('Blagoje', 'Valosic', 1, 'M', 21, 'Beograd'),
    ('Ilija', 'Kaprocki', 4, 'M', 67, 'Novi Sad'),
    ('Aleksandar', 'Misic', 2, 'M', 50, 'Novi Sad'),
    ('Irina', 'Rapaic', 9, 'Z', 72, 'Novi Sad'),
    ('Simeon', 'Bosnjak', 3, 'M', 61, 'Zrenjanin'),
    ('Tijana', 'Tomic', 13, 'Z', 63, 'Zrenjanin'),
    ('Stefan', 'Pijetlovic', 1, 'M', 36, 'Zrenjanin'),
    ('Milos', 'Kamenko', 1, 'M', 31, 'Nis'),
    ('Zoran', 'Misic', 3, 'M', 21, 'Beograd'),
    ('Spomenka', 'Misic', 9, 'Z', 36, 'Novi Sad'),
    ('Katarina', 'Pijetlovic', 9, 'Z', 15, 'Zrenjanin'),
    ('Danica', 'Paroski', 7, 'Z', 15, 'Zrenjanin'),
    ('Marija', 'Zlatanovic', 4, 'Z', 39, 'Novi Sad'),
    ('Vasilije', 'Nenadic', 3, 'M', 61, 'Novi Sad'),
    ('Dijana', 'Jocic', 3, 'Z', 17, 'Zrenjanin'),
    ('Katarina', 'Lakic', 6, 'Z', 79, 'Novi Sad'),
    ('Irena', 'Pijetlovic', 5, 'Z', 25, 'Novi Sad'),
    ('Tijana', 'Kecman', 2, 'Z', 22, 'Nis'),
    ('Spomenka', 'Mikic', 1, 'Z', 12, 'Nis'),
    ('Irena', 'Markovic', 4, 'Z', 70, 'Beograd'),
    ('Zivojin', 'Valosic', 4, 'M', 58, 'Novi Sad'),
    ('Marko', 'Pijetlovic', 4, 'M', 46, 'Beograd'),
    ('Dionizij', 'Tomic', 6, 'M', 64, 'Novi Sad'),
    ('Milica', 'Pijetlovic', 7, 'Z', 58, 'Beograd'),
    ('Ognjen', 'Kamenko', 2, 'M', 24, 'Nis'),
    ('Dragan', 'Nikolic', 5, 'M', 36, 'Beograd'),
    ('Tanja', 'Tomic', 5, 'Z', 49, 'Nis'),
    ('Milica', 'Valosic', 13, 'Z', 67, 'Nis'),
    ('Vasilije', 'Mikic', 5, 'M', 73, 'Zrenjanin'),
    ('Danica', 'Mikic', 8, 'Z', 67, 'Zrenjanin'),
    ('Mirjana', 'Nenadic', 2, 'Z', 18, 'Beograd'),
    ('Mirjana', 'Dulovic', 10, 'Z', 35, 'Zrenjanin'),
    ('Sanja', 'Pijetlovic', 4, 'Z', 42, 'Nis'),
    ('Jovan', 'Rapaic', 7, 'M', 79, 'Zrenjanin'),
    ('Milos', 'Opacic', 8, 'M', 58, 'Nis'),
    ('Milos', 'Pijetlovic', 4, 'M', 19, 'Novi Sad'),
    ('Dragan', 'Kamenko', 0, 'M', 40, 'Nis'),
    ('Nenad', 'Opacic', 3, 'M', 32, 'Nis'),
    ('Tanja', 'Opacic', 11, 'Z', 76, 'Zrenjanin'),
    ('Vukan', 'Valosic', 4, 'M', 36, 'Nis'),
    ('Blagoje', 'Zlatanovic', 8, 'M', 48, 'Novi Sad'),
    ('Ognjen', 'Kaprocki', 3, 'M', 47, 'Nis'),
    ('Ilija', 'Misic', 5, 'M', 54, 'Zrenjanin'),
    ('Dionizij', 'Kaprocki', 7, 'M', 77, 'Beograd'),
    ('Vukasine', 'Zlatanovic', 9, 'M', 23, 'Zrenjanin'),
    ('Marina', 'Dulovic', 4, 'Z', 74, 'Nis'),
    ('Katarina', 'Lakic', 11, 'Z', 55, 'Zrenjanin'),
    ('Jovana', 'Nikolic', 2, 'Z', 19, 'Beograd'),
    ('Sanja', 'Kanovic', 5, 'Z', 59, 'Beograd'),
    ('Spomenka', 'Kecman', 10, 'Z', 10, 'Novi Sad'),
    ('Marko', 'Mikic', 6, 'M', 20, 'Zrenjanin'),
    ('Zoran', 'Kanovic', 4, 'M', 75, 'Beograd'),
    ('Tanja', 'Kanovic', 4, 'Z', 73, 'Nis'),
    ('Petar', 'Pijetlovic', 7, 'M', 74, 'Zrenjanin'),
    ('Dragana', 'Tomic', 4, 'Z', 35, 'Novi Sad'),
    ('Zivojin', 'Lakic', 4, 'M', 73, 'Nis'),
    ('Milos', 'Dulovic', 5, 'M', 13, 'Novi Sad'),
    ('Aleksandar', 'Lakic', 6, 'M', 16, 'Zrenjanin'),
    ('Vasilije', 'Kamenko', 7, 'M', 29, 'Zrenjanin'),
    ('Dionizij', 'Kanovic', 5, 'M', 74, 'Beograd'),
    ('Dionizij', 'Paroski', 0, 'M', 37, 'Nis'),
    ('Marija', 'Rapaic', 10, 'Z', 70, 'Zrenjanin'),
    ('Jelisaveta', 'Zlatanovic', 2, 'Z', 25, 'Beograd'),
    ('Mirjana', 'Rapaic', 8, 'Z', 76, 'Nis'),
    ('Vesna', 'Nikolic', 10, 'Z', 65, 'Zrenjanin'),
    ('Sanja', 'Paroski', 9, 'Z', 39, 'Zrenjanin'),
    ('Aleksandar', 'Paroski', 2, 'M', 41, 'Nis'),
    ('Zoran', 'Kamenko', 5, 'M', 17, 'Zrenjanin'),
    ('Luka', 'Valosic', 10, 'M', 57, 'Zrenjanin'),
    ('Nikola', 'Tomic', 2, 'M', 35, 'Nis'),
    ('Nikola', 'Dulovic', 2, 'M', 42, 'Nis'),
    ('Zivojin', 'Misic', 6, 'M', 33, 'Novi Sad'),
    ('Dragan', 'Lakic', 7, 'M', 31, 'Zrenjanin'),
    ('Sanja', 'Kanovic', 4, 'Z', 47, 'Nis'),
    ('Nikola', 'Valosic', 1, 'M', 33, 'Nis'),
    ('Jovana', 'Kaprocki', 8, 'Z', 56, 'Beograd'),
    ('Stefana', 'Markovic', 6, 'Z', 50, 'Nis'),
    ('Marko', 'Tomic', 7, 'M', 58, 'Zrenjanin'),
    ('Sanja', 'Kecman', 2, 'Z', 35, 'Zrenjanin'),
    ('Nikola', 'Jocic', 4, 'M', 29, 'Beograd'),
    ('Marko', 'Paroski', 4, 'M', 66, 'Beograd'),
    ('Tijana', 'Tomic', 6, 'Z', 10, 'Zrenjanin'),
    ('Stefan', 'Pijetlovic', 5, 'M', 13, 'Novi Sad'),
    ('Ugljesa', 'Nenadic', 0, 'M', 47, 'Novi Sad'),
    ('Irina', 'Nenadic', 6, 'Z', 12, 'Beograd'),
    ('Aleksandar', 'Markovic', 9, 'M', 68, 'Beograd'),
    ('Vesna', 'Kecman', 6, 'Z', 30, 'Zrenjanin'),
    ('Vukan', 'Kamenko', 0, 'M', 41, 'Nis'),
    ('Katarina', 'Misic', 7, 'Z', 38, 'Zrenjanin'),
    ('Nikola', 'Bosnjak', 8, 'M', 65, 'Novi Sad'),
    ('Aleksandar', 'Zlatanovic', 10, 'M', 58, 'Zrenjanin'),
    ('Nenad', 'Kamenko', 5, 'M', 72, 'Beograd'),
    ('Marija', 'Markovic', 6, 'Z', 10, 'Zrenjanin'),
    ('Renata', 'Kecman', 3, 'Z', 31, 'Beograd'),
    ('Marko', 'Lakic', 6, 'M', 33, 'Zrenjanin'),
    ('Sanja', 'Opacic', 5, 'Z', 24, 'Beograd'),
    ('Vuk', 'Misic', 3, 'M', 19, 'Nis'),
    ('Dusan', 'Pijetlovic', 3, 'M', 10, 'Nis'),
    ('Tanja', 'Markovic', 7, 'Z', 33, 'Zrenjanin'),
    ('Zivojin', 'Mikic', 8, 'M', 19, 'Zrenjanin'),
    ('Tanja', 'Valosic', 6, 'Z', 11, 'Nis'),
    ('Ana', 'Mikic', 5, 'Z', 17, 'Beograd'),
    ('Spomenka', 'Lakic', 6, 'Z', 29, 'Zrenjanin'),
    ('Milica', 'Mikic', 5, 'Z', 25, 'Nis'),
    ('Nikola', 'Markovic', 3, 'M', 33, 'Novi Sad'),
    ('Zarko', 'Opacic', 3, 'M', 40, 'Beograd'),
    ('Sanja', 'Bosnjak', 11, 'Z', 57, 'Novi Sad'),
    ('Katarina', 'Markovic', 9, 'Z', 18, 'Zrenjanin'),
    ('Vukan', 'Kaprocki', 0, 'M', 44, 'Beograd'),
    ('Simeon', 'Jocic', 7, 'M', 46, 'Novi Sad'),
    ('Renata', 'Mikic', 7, 'Z', 67, 'Zrenjanin'),
    ('Vasilije', 'Lakic', 4, 'M', 32, 'Nis'),
    ('Marko', 'Valosic', 1, 'M', 78, 'Nis'),
    ('Nikola', 'Kamenko', 1, 'M', 24, 'Novi Sad'),
    ('Sanja', 'Jocic', 4, 'Z', 65, 'Nis'),
    ('Zoran', 'Nenadic', 7, 'M', 56, 'Zrenjanin'),
    ('Jelisaveta', 'Valosic', 7, 'Z', 63, 'Novi Sad'),
    ('Zeljko', 'Lakic', 5, 'M', 11, 'Zrenjanin'),
    ('Milos', 'Zlatanovic', 2, 'M', 73, 'Beograd'),
    ('Marko', 'Kamenko', 6, 'M', 58, 'Beograd'),
    ('Dijana', 'Pijetlovic', 4, 'Z', 72, 'Novi Sad'),
    ('Ilija', 'Zlatanovic', 6, 'M', 61, 'Novi Sad'),
    ('Petar', 'Lakic', 8, 'M', 69, 'Novi Sad'),
    ('Katarina', 'Nenadic', 7, 'Z', 53, 'Beograd'),
    ('Stefan', 'Kaprocki', 8, 'M', 54, 'Beograd'),
    ('Vukan', 'Paroski', 0, 'M', 17, 'Nis'),
    ('Vasilije', 'Misic', 3, 'M', 12, 'Beograd'),
    ('Ana', 'Kanovic', 5, 'Z', 57, 'Novi Sad'),
    ('Sanja', 'Mikic', 8, 'Z', 36, 'Zrenjanin'),
    ('Ilija', 'Zlatanovic', 5, 'M', 42, 'Novi Sad'),
    ('Jelisaveta', 'Nenadic', 9, 'Z', 32, 'Zrenjanin'),
    ('Renata', 'Tomic', 8, 'Z', 64, 'Novi Sad'),
    ('Ilija', 'Zlatanovic', 5, 'M', 64, 'Novi Sad'),
    ('Ilija', 'Jocic', 6, 'M', 77, 'Nis'),
    ('Dragan', 'Markovic', 2, 'M', 24, 'Nis'),
    ('Simeon', 'Kaprocki', 3, 'M', 12, 'Nis'),
    ('Marko', 'Tomic', 7, 'M', 63, 'Novi Sad'),
    ('Zarko', 'Valosic', 6, 'M', 48, 'Novi Sad'),
    ('Dijana', 'Jocic', 4, 'Z', 37, 'Novi Sad'),
    ('Nikola', 'Rapaic', 5, 'M', 70, 'Beograd'),
    ('Zoran', 'Zlatanovic', 5, 'M', 54, 'Novi Sad'),
    ('Jelisaveta', 'Tomic', 9, 'Z', 74, 'Novi Sad'),
    ('Irina', 'Rapaic', 5, 'Z', 43, 'Beograd'),
    ('Nikola', 'Opacic', 3, 'M', 31, 'Nis'),
    ('Milan', 'Valosic', 2, 'M', 73, 'Beograd'),
    ('Marina', 'Mikic', 6, 'Z', 67, 'Nis'),
    ('Dijana', 'Kamenko', 8, 'Z', 56, 'Zrenjanin'),
    ('Petar', 'Zlatanovic', 1, 'M', 74, 'Novi Sad'),
    ('Jovana', 'Opacic', 9, 'Z', 69, 'Novi Sad'),
    ('Luka', 'Kecman', 6, 'M', 46, 'Novi Sad'),
    ('Zeljko', 'Markovic', 5, 'M', 46, 'Zrenjanin'),
    ('Vesna', 'Valosic', 4, 'Z', 17, 'Beograd'),
    ('Dusan', 'Kanovic', 7, 'M', 61, 'Beograd'),
    ('Jelisaveta', 'Kanovic', 4, 'Z', 70, 'Nis'),
    ('Tijana', 'Lakic', 4, 'Z', 69, 'Nis'),
    ('Jelisaveta', 'Kamenko', 5, 'Z', 16, 'Nis'),
    ('Spomenka', 'Nenadic', 9, 'Z', 51, 'Beograd'),
    ('Marina', 'Mikic', 6, 'Z', 27, 'Nis'),
    ('Danica', 'Mikic', 8, 'Z', 11, 'Zrenjanin'),
    ('Marina', 'Pijetlovic', 7, 'Z', 51, 'Zrenjanin'),
    ('Tijana', 'Kanovic', 0, 'Z', 14, 'Nis'),
    ('Stefana', 'Paroski', 6, 'Z', 44, 'Zrenjanin'),
    ('Irina', 'Lakic', 7, 'Z', 68, 'Zrenjanin');